JOSS paper
Simulation-Decomposition/simdec-python pull request #23
Opened 2023-10-31 22:37 UTC by tupui

2023-10-31 22:43 UTC, tupui commented
The structure is there, now "just" need to do some writing 😅 It's a one page thing, I should be able to do that (and could help with what needs to end up in the book??)

Only the md and bib files need to be edited. To see how it renders, push on the branch and you can look at the automatic action `Paper Draft (push)`:
<img width="816" alt="Screenshot 2023-10-31 at 23 42 03" src="https://github.com/Simulation-Decomposition/simdec-python/assets/23188539/2cf12b2a-4d8a-4dd7-86bd-e2184d3735dc">

Then click summary and download the artifact:

<img width="1193" alt="Screenshot 2023-10-31 at 23 42 50" src="https://github.com/Simulation-Decomposition/simdec-python/assets/23188539/d935859c-d46e-46f3-88bd-f0171ab59142">

We cannot change anything to the styling, everything is done automagically and there is no tuning allowed.

cc @gnopik

2024-04-09 23:33 UTC, tupui commented
@gnopik I pushed a quick update. Besides the info there that I need to rework slightly, is there anything special you want to see here? I guess at least 1-2 citations for SimDec itself, something else?

2024-04-11 15:59 UTC, gnopik commented on joss/paper.md
> +The authors thank ...
The work on this open-source software was supported by grant #220177 from Finnish Foundation for Economic Foundation

2024-04-11 16:00 UTC, gnopik commented on joss/paper.md
> +Uncertainties are everywhere! Whether you are developing a new AI system,
Suggestion to use "." instead of "!"

2024-04-11 16:01 UTC, gnopik requested changes
All good, see two minor comments and the addition to the acknowledgments.

2024-05-29 09:19 UTC, tupui commented on joss/paper.md
> +impact assessments of systems under uncertainties.
```suggestion
From real life experiments to numerical simulations, uncertainties play a
crucial role in the system under study. With the advent of Artificial
Intelligence and new regulations such the [AI Act](https://artificialintelligenceact.eu) or the
*Better Regulation Guideline* [@europeancommission2021], there is a growing need for explainability and
impact assessments of systems under uncertainties.
```

2024-05-29 10:02 UTC, gnopik commented on joss/paper.md
> +results.
```suggestion
influence the system. Therefore, an approach is needed to understand how these uncertainties impact the system's performance.
```

2024-05-29 10:06 UTC, gnopik commented on joss/paper.md
> +dashboard, making uncertainty analysis accessible to everyone.
```suggestion
uncertainties play. A clear Python Application Programming Interface (API) and a no-code interactive web
dashboard make uncertainty analysis accessible to everyone.
```

2024-05-29 10:14 UTC, gnopik commented on joss/paper.md
> +influential input variables. The resulting visualization shows how different
```suggestion
dataset [@Kozlova2024]. It decomposes the distribution of the output
(target variable) by automatically forming scenarios that reveal the most critical behavior of the system. The scenarios are formed out of the most influential input variables (defined with variance-based sensitivity indices) by breaking down their numeric ranges into states (e.g. low and high) and creating an exhaustive list of their combinations (e.g. (i) low A & low B, (ii) low A & high B, (iii) high A & low B, and (iv) high A and high B). The resulting visualization shows how different
```

2024-05-29 10:26 UTC, gnopik commented on joss/paper.md
> +![SimDec: explanation of output by most important inputs.\label{fig:simdec}](simdec_presentation.png)
```suggestion
![SimDec: explanation of output by most important inputs. A simulation dataset of a structural reliability model with one key output variable and four input variables is used for this case. Inputs 3 and 1 have the highest sensitivity indices and thus are automatically chosen for decomposition. The most influential input 3 divides the distribution of the output into three main states with distinct colors. Input 1 further subdivides them into shades. From the graph, it becomes obvious that input 1 influences the output when input 3 is low, but has a negligible effect when input 3 is medium or high.\label{fig:simdec}](simdec_presentation.png)
```

2024-05-29 10:27 UTC, gnopik commented on joss/paper.md
> +relies on powerful methods from SALib [@Herman2017] and
```suggestion
relies on powerful variance-based sensitivity analysis methods from SALib [@Herman2017] and
```

2024-05-29 10:32 UTC, gnopik commented on joss/paper.md
> +dataset [@Kozlova2024]. It decomposes the distribution of the output
```suggestion
Simulation Decomposition or SimDec moves the field of SA forward by supplementing the computation of sensitivity indices with the visualization of the type of interactions involved, which proves critical for understanding the system's behavior and decision-making [@Kozlova2024]. 
In short, SimDec is a hybrid uncertainty-sensitivity analysis approach
that reveals the critical behavior of a computational model or an empirical
dataset. It decomposes the distribution of the output
```

2024-05-30 09:37 UTC, tupui commented
@gnopik I added notebook support. See https://simdec--23.org.readthedocs.build/en/23/notebooks/structural_reliability.html

2024-05-30 09:37 UTC, matt-graham commented on joss/paper.md
> +the output–as seen in \autoref{fig:simdec}. The method has shown value for
```suggestion
the output—as seen in \autoref{fig:simdec}. The method has shown value for
```

2024-05-30 09:37 UTC, matt-graham commented on joss/paper.md
> +Intelligence and new regulations such as the [AI Act](https://artificialintelligenceact.eu) or the
```suggestion
crucial role in the system under study. With the advent of AI
and new regulations such as the [AI Act](https://artificialintelligenceact.eu) or the
```
As acronym already defined above

2024-05-30 09:39 UTC, tupui commented
Thank you @matt-graham, done.

2024-06-05 00:21 UTC, tupui commented
Alright, the paper is approved 🎉 Getting this in and cutting a release now for the process.

2024-06-05 00:22 UTC, merged